server:
  port: 8082

spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cineverse}


file:
  upload-dir: /Users/arinsingh/summpercamp/cineverse/backend/movie-service/uploads
